### ISSUE TITLE
code finished?

### ISSUE THREAD

**Issue by lixiang-ucas** [jasjeetIM/Mask-RCNN#1]
Hi, jasjeetlM, have you successfully train mask rcnn with this code?

**Comment by jasjeetIM** [comment]
Hi,

I have not spent much time training the models and have not been able to find the right set of hyper parameters yet. I hope to do so over the next few weeks.

Thanks

**Comment by lixiang-ucas** [comment]
thanks, i'm looking forward to your exciting work!

**Comment by ShihuaHuang95** [comment]
How about now？
