### ISSUE TITLE
prototxts for RPN and Mask RCNN training

### ISSUE THREAD

**Issue by realwecan** [jasjeetIM/Mask-RCNN#4]
I was wondering if we should supply prototxt files in a folder named "models". Specifically, we need them in "rpn_prototxts" and "mask_rcnn_prototxts" subfolders for training RPN and masks, respectively. It seems that the current code does not provide these files.

@jasjeetIM Would you please be kind enough to share these prototxt files in a ResNet-50 model for our reference? Your help and advice will be greatly appreciated.

Thank you!

**Comment by LeThaiSon** [comment]
@jasjeetIM Hope you can share the model files with us for reference. Thank you in advance!

**Comment by jasjeetIM** [comment]
Hello, 

I have added the prototxt files that define the model. However, I have not had time to train the models and will not be be able to train them in the near future due to other work. 

Hope the existing code/files can assist you.

**Comment by soulslicer** [comment]
Hi has anyone been able to make this work?
